
services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "10018:8069"
    tty: true
    # Added "-i base" to initialize the database
    command: odoo -d postgres --db_host db --db_user odoo --db_password odoo18@2024 -i base
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2024
      - PIP_BREAK_SYSTEM_PACKAGES=1
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    restart: always

volumes:
  odoo-data:
