services:
  db:
    image: postgres:18
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo19@2025
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      # Using the version-specific path required for PostgreSQL 18+
      - ./postgresql:/var/lib/postgresql/18/docker

  odoo19:
    image: odoo:19
    user: root
    depends_on:
      - db
    ports:
      - "10019:8069"
      - "20019:8072"
    tty: true
    # Initializing the 'postgres' database as per your Odoo 18 logic
    command: odoo -d postgres --db_host db --db_user odoo --db_password odoo19@2025 -i base
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo19@2025
      - PIP_BREAK_SYSTEM_PACKAGES=1
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - odoo-data:/var/lib/odoo
    restart: always

volumes:
  odoo-data:
